TRUNCATE b_task_operation;
TRUNCATE b_tasks_viewed;
TRUNCATE b_tasks_timer;
TRUNCATE b_tasks_template_dep;
TRUNCATE b_tasks_template_chl_item;
TRUNCATE b_tasks_template;
TRUNCATE b_tasks_task_template_access;
TRUNCATE b_tasks_task_stage;
TRUNCATE b_tasks_task_parameter;
TRUNCATE b_tasks_task_dep;
TRUNCATE b_tasks_tag;
TRUNCATE b_tasks_syslog;
TRUNCATE b_tasks_stages;
TRUNCATE b_tasks_sorting;
TRUNCATE b_tasks_reminder;
TRUNCATE b_tasks_proj_dep;
TRUNCATE b_tasks_projects;
TRUNCATE b_tasks_msg_throttle;
TRUNCATE b_tasks_member;
TRUNCATE b_tasks_log;
TRUNCATE b_tasks_filters;
TRUNCATE b_tasks_files_temporary;
TRUNCATE b_tasks_file;
TRUNCATE b_tasks_favorite;
TRUNCATE b_tasks_elapsed_time;
TRUNCATE b_tasks_effective;
TRUNCATE b_tasks_dependence;
TRUNCATE b_tasks_counters;
TRUNCATE b_tasks_columns;
TRUNCATE b_tasks_checklist_items;
TRUNCATE b_tasks;
TRUNCATE b_task;
select * from test;

ALTER TABLE test_table MODIFY ID int NOT NULL AFTER USER_ID
INSERT INTO b_task SELECT * FROM import_b_task;
INSERT INTO b_tasks SELECT * FROM import_b_tasks;
INSERT INTO b_tasks_checklist_items SELECT * FROM import_b_tasks_checklist_items;
INSERT INTO b_tasks_columns SELECT * FROM import_b_tasks_columns;
INSERT INTO b_tasks_counters SELECT * FROM import_b_tasks_counters;
INSERT INTO b_tasks_dependence SELECT * FROM import_b_tasks_dependence;
INSERT INTO b_tasks_effective SELECT * FROM import_b_tasks_effective;
INSERT INTO b_tasks_elapsed_time SELECT * FROM import_b_tasks_elapsed_time;
INSERT INTO b_tasks_favorite SELECT * FROM import_b_tasks_favorite;
INSERT INTO b_tasks_file SELECT * FROM import_b_tasks_file;
INSERT INTO b_tasks_files_temporary SELECT * FROM import_b_tasks_files_temporary;
INSERT INTO b_tasks_filters SELECT * FROM import_b_tasks_filters;
INSERT INTO b_tasks_log SELECT * FROM import_b_tasks_log;
INSERT INTO b_tasks_member SELECT * FROM import_b_tasks_member;
INSERT INTO b_tasks_msg_throttle SELECT * FROM import_b_tasks_msg_throttle;
INSERT INTO b_tasks_projects SELECT * FROM import_b_tasks_projects;
INSERT INTO b_tasks_proj_dep SELECT * FROM import_b_tasks_proj_dep;
INSERT INTO b_tasks_reminder SELECT * FROM import_b_tasks_reminder;
INSERT INTO b_tasks_sorting SELECT * FROM import_b_tasks_sorting;
INSERT INTO b_tasks_stages SELECT * FROM import_b_tasks_stages;
INSERT INTO b_tasks_syslog SELECT * FROM import_b_tasks_syslog;
INSERT INTO b_tasks_tag SELECT * FROM import_b_tasks_tag;
INSERT INTO b_tasks_task_dep SELECT * FROM import_b_tasks_task_dep;
INSERT INTO b_tasks_task_parameter SELECT * FROM import_b_tasks_task_parameter;
INSERT INTO b_tasks_task_stage SELECT * FROM import_b_tasks_task_stage;
INSERT INTO b_tasks_task_template_access SELECT * FROM import_b_tasks_task_template_access;
INSERT INTO b_tasks_template SELECT * FROM import_b_tasks_template;
INSERT INTO b_tasks_template_chl_item SELECT * FROM import_b_tasks_template_chl_item;
INSERT INTO b_tasks_template_dep SELECT * FROM import_b_tasks_template_dep;
INSERT INTO b_tasks_timer SELECT * FROM import_b_tasks_timer;
INSERT INTO b_tasks_viewed SELECT * FROM import_b_tasks_viewed;
INSERT INTO b_task_operation SELECT * FROM import_b_task_operation;
